from ._nav_cancel import *
from ._nav_delete_path import *
from ._nav_get_patrol_name import *
from ._nav_get_status import *
from ._nav_list_path import *
from ._nav_mag_calibra import *
from ._nav_path_save import *
from ._nav_path_start import *
from ._nav_patrol import *
from ._nav_patrol_stop import *
from ._record_clean import *
from ._record_delete_file import *
from ._record_get_file_num import *
from ._record_get_file_path import *
from ._record_get_files import *
from ._record_get_status import *
from ._record_start import *
from ._record_stop import *
from ._rtmp_start import *
from ._rtmp_stop import *
from ._sched_add_mod import *
from ._video_set_resolution import *
from ._wifi_scan_list import *
from ._wifi_switch_mode import *
from ._wifi_switch_ssid_key import *
