# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from roller_eye/sched_add_modRequest.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import roller_eye.msg

class sched_add_modRequest(genpy.Message):
  _md5sum = "cc1faf861ce145533cfd6c3511ccd1dd"
  _type = "roller_eye/sched_add_modRequest"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """task tsk

================================================================================
MSG: roller_eye/task
int32 id
string name
string type
int8 repeateType
int8[] repeateDays
int32 timeYear
int8 timeMonth
int8 timeDay
int8 timeHour
int8 timeMinute
int8 timeSecond
int32 expire
string param
bool notice
bool active"""
  __slots__ = ['tsk']
  _slot_types = ['roller_eye/task']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       tsk

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(sched_add_modRequest, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.tsk is None:
        self.tsk = roller_eye.msg.task()
    else:
      self.tsk = roller_eye.msg.task()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.tsk.id
      buff.write(_get_struct_i().pack(_x))
      _x = self.tsk.name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.tsk.type
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.tsk.repeateType
      buff.write(_get_struct_b().pack(_x))
      length = len(self.tsk.repeateDays)
      buff.write(_struct_I.pack(length))
      pattern = '<%sb'%length
      buff.write(struct.Struct(pattern).pack(*self.tsk.repeateDays))
      _x = self
      buff.write(_get_struct_i5bi().pack(_x.tsk.timeYear, _x.tsk.timeMonth, _x.tsk.timeDay, _x.tsk.timeHour, _x.tsk.timeMinute, _x.tsk.timeSecond, _x.tsk.expire))
      _x = self.tsk.param
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2B().pack(_x.tsk.notice, _x.tsk.active))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.tsk is None:
        self.tsk = roller_eye.msg.task()
      end = 0
      start = end
      end += 4
      (self.tsk.id,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.tsk.name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.tsk.name = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.tsk.type = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.tsk.type = str[start:end]
      start = end
      end += 1
      (self.tsk.repeateType,) = _get_struct_b().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sb'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.tsk.repeateDays = s.unpack(str[start:end])
      _x = self
      start = end
      end += 13
      (_x.tsk.timeYear, _x.tsk.timeMonth, _x.tsk.timeDay, _x.tsk.timeHour, _x.tsk.timeMinute, _x.tsk.timeSecond, _x.tsk.expire,) = _get_struct_i5bi().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.tsk.param = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.tsk.param = str[start:end]
      _x = self
      start = end
      end += 2
      (_x.tsk.notice, _x.tsk.active,) = _get_struct_2B().unpack(str[start:end])
      self.tsk.notice = bool(self.tsk.notice)
      self.tsk.active = bool(self.tsk.active)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.tsk.id
      buff.write(_get_struct_i().pack(_x))
      _x = self.tsk.name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.tsk.type
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.tsk.repeateType
      buff.write(_get_struct_b().pack(_x))
      length = len(self.tsk.repeateDays)
      buff.write(_struct_I.pack(length))
      pattern = '<%sb'%length
      buff.write(self.tsk.repeateDays.tostring())
      _x = self
      buff.write(_get_struct_i5bi().pack(_x.tsk.timeYear, _x.tsk.timeMonth, _x.tsk.timeDay, _x.tsk.timeHour, _x.tsk.timeMinute, _x.tsk.timeSecond, _x.tsk.expire))
      _x = self.tsk.param
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2B().pack(_x.tsk.notice, _x.tsk.active))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.tsk is None:
        self.tsk = roller_eye.msg.task()
      end = 0
      start = end
      end += 4
      (self.tsk.id,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.tsk.name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.tsk.name = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.tsk.type = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.tsk.type = str[start:end]
      start = end
      end += 1
      (self.tsk.repeateType,) = _get_struct_b().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sb'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.tsk.repeateDays = numpy.frombuffer(str[start:end], dtype=numpy.int8, count=length)
      _x = self
      start = end
      end += 13
      (_x.tsk.timeYear, _x.tsk.timeMonth, _x.tsk.timeDay, _x.tsk.timeHour, _x.tsk.timeMinute, _x.tsk.timeSecond, _x.tsk.expire,) = _get_struct_i5bi().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.tsk.param = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.tsk.param = str[start:end]
      _x = self
      start = end
      end += 2
      (_x.tsk.notice, _x.tsk.active,) = _get_struct_2B().unpack(str[start:end])
      self.tsk.notice = bool(self.tsk.notice)
      self.tsk.active = bool(self.tsk.active)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2B = None
def _get_struct_2B():
    global _struct_2B
    if _struct_2B is None:
        _struct_2B = struct.Struct("<2B")
    return _struct_2B
_struct_b = None
def _get_struct_b():
    global _struct_b
    if _struct_b is None:
        _struct_b = struct.Struct("<b")
    return _struct_b
_struct_i = None
def _get_struct_i():
    global _struct_i
    if _struct_i is None:
        _struct_i = struct.Struct("<i")
    return _struct_i
_struct_i5bi = None
def _get_struct_i5bi():
    global _struct_i5bi
    if _struct_i5bi is None:
        _struct_i5bi = struct.Struct("<i5bi")
    return _struct_i5bi
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from roller_eye/sched_add_modResponse.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class sched_add_modResponse(genpy.Message):
  _md5sum = "c5e4a7d59c68f74eabcec876a00216aa"
  _type = "roller_eye/sched_add_modResponse"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int32 id


"""
  __slots__ = ['id']
  _slot_types = ['int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       id

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(sched_add_modResponse, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.id is None:
        self.id = 0
    else:
      self.id = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.id
      buff.write(_get_struct_i().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (self.id,) = _get_struct_i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.id
      buff.write(_get_struct_i().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (self.id,) = _get_struct_i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_i = None
def _get_struct_i():
    global _struct_i
    if _struct_i is None:
        _struct_i = struct.Struct("<i")
    return _struct_i
class sched_add_mod(object):
  _type          = 'roller_eye/sched_add_mod'
  _md5sum = 'e0be7b42d9f9c638e488c09d9f0ede84'
  _request_class  = sched_add_modRequest
  _response_class = sched_add_modResponse
