// Generated by gencpp from file roller_eye/nav_patrolResponse.msg
// DO NOT EDIT!


#ifndef ROLLER_EYE_MESSAGE_NAV_PATROLRESPONSE_H
#define ROLLER_EYE_MESSAGE_NAV_PATROLRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roller_eye
{
template <class ContainerAllocator>
struct nav_patrolResponse_
{
  typedef nav_patrolResponse_<ContainerAllocator> Type;

  nav_patrolResponse_()
    : ret(0)  {
    }
  nav_patrolResponse_(const ContainerAllocator& _alloc)
    : ret(0)  {
  (void)_alloc;
    }



   typedef int32_t _ret_type;
  _ret_type ret;





  typedef boost::shared_ptr< ::roller_eye::nav_patrolResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roller_eye::nav_patrolResponse_<ContainerAllocator> const> ConstPtr;

}; // struct nav_patrolResponse_

typedef ::roller_eye::nav_patrolResponse_<std::allocator<void> > nav_patrolResponse;

typedef boost::shared_ptr< ::roller_eye::nav_patrolResponse > nav_patrolResponsePtr;
typedef boost::shared_ptr< ::roller_eye::nav_patrolResponse const> nav_patrolResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roller_eye::nav_patrolResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roller_eye::nav_patrolResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::roller_eye::nav_patrolResponse_<ContainerAllocator1> & lhs, const ::roller_eye::nav_patrolResponse_<ContainerAllocator2> & rhs)
{
  return lhs.ret == rhs.ret;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::roller_eye::nav_patrolResponse_<ContainerAllocator1> & lhs, const ::roller_eye::nav_patrolResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace roller_eye

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::roller_eye::nav_patrolResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roller_eye::nav_patrolResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roller_eye::nav_patrolResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roller_eye::nav_patrolResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roller_eye::nav_patrolResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roller_eye::nav_patrolResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roller_eye::nav_patrolResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3bd113e2f12c9c571d32a0bd71d59b8d";
  }

  static const char* value(const ::roller_eye::nav_patrolResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3bd113e2f12c9c57ULL;
  static const uint64_t static_value2 = 0x1d32a0bd71d59b8dULL;
};

template<class ContainerAllocator>
struct DataType< ::roller_eye::nav_patrolResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roller_eye/nav_patrolResponse";
  }

  static const char* value(const ::roller_eye::nav_patrolResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roller_eye::nav_patrolResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 ret\n"
;
  }

  static const char* value(const ::roller_eye::nav_patrolResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roller_eye::nav_patrolResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ret);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct nav_patrolResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roller_eye::nav_patrolResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roller_eye::nav_patrolResponse_<ContainerAllocator>& v)
  {
    s << indent << "ret: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ret);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROLLER_EYE_MESSAGE_NAV_PATROLRESPONSE_H
