// Generated by gencpp from file roller_eye/nav_path_save.msg
// DO NOT EDIT!


#ifndef ROLLER_EYE_MESSAGE_NAV_PATH_SAVE_H
#define ROLLER_EYE_MESSAGE_NAV_PATH_SAVE_H

#include <ros/service_traits.h>


#include <roller_eye/nav_path_saveRequest.h>
#include <roller_eye/nav_path_saveResponse.h>


namespace roller_eye
{

struct nav_path_save
{

typedef nav_path_saveRequest Request;
typedef nav_path_saveResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct nav_path_save
} // namespace roller_eye


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::roller_eye::nav_path_save > {
  static const char* value()
  {
    return "c1f3d28f1b044c871e6eff2e9fc3c667";
  }

  static const char* value(const ::roller_eye::nav_path_save&) { return value(); }
};

template<>
struct DataType< ::roller_eye::nav_path_save > {
  static const char* value()
  {
    return "roller_eye/nav_path_save";
  }

  static const char* value(const ::roller_eye::nav_path_save&) { return value(); }
};


// service_traits::MD5Sum< ::roller_eye::nav_path_saveRequest> should match
// service_traits::MD5Sum< ::roller_eye::nav_path_save >
template<>
struct MD5Sum< ::roller_eye::nav_path_saveRequest>
{
  static const char* value()
  {
    return MD5Sum< ::roller_eye::nav_path_save >::value();
  }
  static const char* value(const ::roller_eye::nav_path_saveRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::roller_eye::nav_path_saveRequest> should match
// service_traits::DataType< ::roller_eye::nav_path_save >
template<>
struct DataType< ::roller_eye::nav_path_saveRequest>
{
  static const char* value()
  {
    return DataType< ::roller_eye::nav_path_save >::value();
  }
  static const char* value(const ::roller_eye::nav_path_saveRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::roller_eye::nav_path_saveResponse> should match
// service_traits::MD5Sum< ::roller_eye::nav_path_save >
template<>
struct MD5Sum< ::roller_eye::nav_path_saveResponse>
{
  static const char* value()
  {
    return MD5Sum< ::roller_eye::nav_path_save >::value();
  }
  static const char* value(const ::roller_eye::nav_path_saveResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::roller_eye::nav_path_saveResponse> should match
// service_traits::DataType< ::roller_eye::nav_path_save >
template<>
struct DataType< ::roller_eye::nav_path_saveResponse>
{
  static const char* value()
  {
    return DataType< ::roller_eye::nav_path_save >::value();
  }
  static const char* value(const ::roller_eye::nav_path_saveResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROLLER_EYE_MESSAGE_NAV_PATH_SAVE_H
