// Generated by gencpp from file roller_eye/nav_path_saveResponse.msg
// DO NOT EDIT!


#ifndef ROLLER_EYE_MESSAGE_NAV_PATH_SAVERESPONSE_H
#define ROLLER_EYE_MESSAGE_NAV_PATH_SAVERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roller_eye
{
template <class ContainerAllocator>
struct nav_path_saveResponse_
{
  typedef nav_path_saveResponse_<ContainerAllocator> Type;

  nav_path_saveResponse_()
    {
    }
  nav_path_saveResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::roller_eye::nav_path_saveResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roller_eye::nav_path_saveResponse_<ContainerAllocator> const> ConstPtr;

}; // struct nav_path_saveResponse_

typedef ::roller_eye::nav_path_saveResponse_<std::allocator<void> > nav_path_saveResponse;

typedef boost::shared_ptr< ::roller_eye::nav_path_saveResponse > nav_path_saveResponsePtr;
typedef boost::shared_ptr< ::roller_eye::nav_path_saveResponse const> nav_path_saveResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roller_eye::nav_path_saveResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roller_eye::nav_path_saveResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace roller_eye

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::roller_eye::nav_path_saveResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roller_eye::nav_path_saveResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roller_eye::nav_path_saveResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roller_eye::nav_path_saveResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roller_eye::nav_path_saveResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roller_eye::nav_path_saveResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roller_eye::nav_path_saveResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::roller_eye::nav_path_saveResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::roller_eye::nav_path_saveResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roller_eye/nav_path_saveResponse";
  }

  static const char* value(const ::roller_eye::nav_path_saveResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roller_eye::nav_path_saveResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::roller_eye::nav_path_saveResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roller_eye::nav_path_saveResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct nav_path_saveResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roller_eye::nav_path_saveResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::roller_eye::nav_path_saveResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ROLLER_EYE_MESSAGE_NAV_PATH_SAVERESPONSE_H
