// Generated by gencpp from file roller_eye/record_delete_file.msg
// DO NOT EDIT!


#ifndef ROLLER_EYE_MESSAGE_RECORD_DELETE_FILE_H
#define ROLLER_EYE_MESSAGE_RECORD_DELETE_FILE_H

#include <ros/service_traits.h>


#include <roller_eye/record_delete_fileRequest.h>
#include <roller_eye/record_delete_fileResponse.h>


namespace roller_eye
{

struct record_delete_file
{

typedef record_delete_fileRequest Request;
typedef record_delete_fileResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct record_delete_file
} // namespace roller_eye


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::roller_eye::record_delete_file > {
  static const char* value()
  {
    return "d174aae7b527c51850235bfe2b29a33b";
  }

  static const char* value(const ::roller_eye::record_delete_file&) { return value(); }
};

template<>
struct DataType< ::roller_eye::record_delete_file > {
  static const char* value()
  {
    return "roller_eye/record_delete_file";
  }

  static const char* value(const ::roller_eye::record_delete_file&) { return value(); }
};


// service_traits::MD5Sum< ::roller_eye::record_delete_fileRequest> should match
// service_traits::MD5Sum< ::roller_eye::record_delete_file >
template<>
struct MD5Sum< ::roller_eye::record_delete_fileRequest>
{
  static const char* value()
  {
    return MD5Sum< ::roller_eye::record_delete_file >::value();
  }
  static const char* value(const ::roller_eye::record_delete_fileRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::roller_eye::record_delete_fileRequest> should match
// service_traits::DataType< ::roller_eye::record_delete_file >
template<>
struct DataType< ::roller_eye::record_delete_fileRequest>
{
  static const char* value()
  {
    return DataType< ::roller_eye::record_delete_file >::value();
  }
  static const char* value(const ::roller_eye::record_delete_fileRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::roller_eye::record_delete_fileResponse> should match
// service_traits::MD5Sum< ::roller_eye::record_delete_file >
template<>
struct MD5Sum< ::roller_eye::record_delete_fileResponse>
{
  static const char* value()
  {
    return MD5Sum< ::roller_eye::record_delete_file >::value();
  }
  static const char* value(const ::roller_eye::record_delete_fileResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::roller_eye::record_delete_fileResponse> should match
// service_traits::DataType< ::roller_eye::record_delete_file >
template<>
struct DataType< ::roller_eye::record_delete_fileResponse>
{
  static const char* value()
  {
    return DataType< ::roller_eye::record_delete_file >::value();
  }
  static const char* value(const ::roller_eye::record_delete_fileResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROLLER_EYE_MESSAGE_RECORD_DELETE_FILE_H
