// Generated by gencpp from file roller_eye/record_get_file_num.msg
// DO NOT EDIT!


#ifndef ROLLER_EYE_MESSAGE_RECORD_GET_FILE_NUM_H
#define ROLLER_EYE_MESSAGE_RECORD_GET_FILE_NUM_H

#include <ros/service_traits.h>


#include <roller_eye/record_get_file_numRequest.h>
#include <roller_eye/record_get_file_numResponse.h>


namespace roller_eye
{

struct record_get_file_num
{

typedef record_get_file_numRequest Request;
typedef record_get_file_numResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct record_get_file_num
} // namespace roller_eye


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::roller_eye::record_get_file_num > {
  static const char* value()
  {
    return "512c7fac39aff0618cf82eac01aae055";
  }

  static const char* value(const ::roller_eye::record_get_file_num&) { return value(); }
};

template<>
struct DataType< ::roller_eye::record_get_file_num > {
  static const char* value()
  {
    return "roller_eye/record_get_file_num";
  }

  static const char* value(const ::roller_eye::record_get_file_num&) { return value(); }
};


// service_traits::MD5Sum< ::roller_eye::record_get_file_numRequest> should match
// service_traits::MD5Sum< ::roller_eye::record_get_file_num >
template<>
struct MD5Sum< ::roller_eye::record_get_file_numRequest>
{
  static const char* value()
  {
    return MD5Sum< ::roller_eye::record_get_file_num >::value();
  }
  static const char* value(const ::roller_eye::record_get_file_numRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::roller_eye::record_get_file_numRequest> should match
// service_traits::DataType< ::roller_eye::record_get_file_num >
template<>
struct DataType< ::roller_eye::record_get_file_numRequest>
{
  static const char* value()
  {
    return DataType< ::roller_eye::record_get_file_num >::value();
  }
  static const char* value(const ::roller_eye::record_get_file_numRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::roller_eye::record_get_file_numResponse> should match
// service_traits::MD5Sum< ::roller_eye::record_get_file_num >
template<>
struct MD5Sum< ::roller_eye::record_get_file_numResponse>
{
  static const char* value()
  {
    return MD5Sum< ::roller_eye::record_get_file_num >::value();
  }
  static const char* value(const ::roller_eye::record_get_file_numResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::roller_eye::record_get_file_numResponse> should match
// service_traits::DataType< ::roller_eye::record_get_file_num >
template<>
struct DataType< ::roller_eye::record_get_file_numResponse>
{
  static const char* value()
  {
    return DataType< ::roller_eye::record_get_file_num >::value();
  }
  static const char* value(const ::roller_eye::record_get_file_numResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROLLER_EYE_MESSAGE_RECORD_GET_FILE_NUM_H
