// Generated by gencpp from file roller_eye/record_get_status.msg
// DO NOT EDIT!


#ifndef ROLLER_EYE_MESSAGE_RECORD_GET_STATUS_H
#define ROLLER_EYE_MESSAGE_RECORD_GET_STATUS_H

#include <ros/service_traits.h>


#include <roller_eye/record_get_statusRequest.h>
#include <roller_eye/record_get_statusResponse.h>


namespace roller_eye
{

struct record_get_status
{

typedef record_get_statusRequest Request;
typedef record_get_statusResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct record_get_status
} // namespace roller_eye


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::roller_eye::record_get_status > {
  static const char* value()
  {
    return "2534c826460bf93cfe607a7e6b3bfe9d";
  }

  static const char* value(const ::roller_eye::record_get_status&) { return value(); }
};

template<>
struct DataType< ::roller_eye::record_get_status > {
  static const char* value()
  {
    return "roller_eye/record_get_status";
  }

  static const char* value(const ::roller_eye::record_get_status&) { return value(); }
};


// service_traits::MD5Sum< ::roller_eye::record_get_statusRequest> should match
// service_traits::MD5Sum< ::roller_eye::record_get_status >
template<>
struct MD5Sum< ::roller_eye::record_get_statusRequest>
{
  static const char* value()
  {
    return MD5Sum< ::roller_eye::record_get_status >::value();
  }
  static const char* value(const ::roller_eye::record_get_statusRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::roller_eye::record_get_statusRequest> should match
// service_traits::DataType< ::roller_eye::record_get_status >
template<>
struct DataType< ::roller_eye::record_get_statusRequest>
{
  static const char* value()
  {
    return DataType< ::roller_eye::record_get_status >::value();
  }
  static const char* value(const ::roller_eye::record_get_statusRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::roller_eye::record_get_statusResponse> should match
// service_traits::MD5Sum< ::roller_eye::record_get_status >
template<>
struct MD5Sum< ::roller_eye::record_get_statusResponse>
{
  static const char* value()
  {
    return MD5Sum< ::roller_eye::record_get_status >::value();
  }
  static const char* value(const ::roller_eye::record_get_statusResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::roller_eye::record_get_statusResponse> should match
// service_traits::DataType< ::roller_eye::record_get_status >
template<>
struct DataType< ::roller_eye::record_get_statusResponse>
{
  static const char* value()
  {
    return DataType< ::roller_eye::record_get_status >::value();
  }
  static const char* value(const ::roller_eye::record_get_statusResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROLLER_EYE_MESSAGE_RECORD_GET_STATUS_H
