// Generated by gencpp from file roller_eye/rtmp_stopRequest.msg
// DO NOT EDIT!


#ifndef ROLLER_EYE_MESSAGE_RTMP_STOPREQUEST_H
#define ROLLER_EYE_MESSAGE_RTMP_STOPREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roller_eye
{
template <class ContainerAllocator>
struct rtmp_stopRequest_
{
  typedef rtmp_stopRequest_<ContainerAllocator> Type;

  rtmp_stopRequest_()
    : app()
    , name()  {
    }
  rtmp_stopRequest_(const ContainerAllocator& _alloc)
    : app(_alloc)
    , name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _app_type;
  _app_type app;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;





  typedef boost::shared_ptr< ::roller_eye::rtmp_stopRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roller_eye::rtmp_stopRequest_<ContainerAllocator> const> ConstPtr;

}; // struct rtmp_stopRequest_

typedef ::roller_eye::rtmp_stopRequest_<std::allocator<void> > rtmp_stopRequest;

typedef boost::shared_ptr< ::roller_eye::rtmp_stopRequest > rtmp_stopRequestPtr;
typedef boost::shared_ptr< ::roller_eye::rtmp_stopRequest const> rtmp_stopRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roller_eye::rtmp_stopRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roller_eye::rtmp_stopRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::roller_eye::rtmp_stopRequest_<ContainerAllocator1> & lhs, const ::roller_eye::rtmp_stopRequest_<ContainerAllocator2> & rhs)
{
  return lhs.app == rhs.app &&
    lhs.name == rhs.name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::roller_eye::rtmp_stopRequest_<ContainerAllocator1> & lhs, const ::roller_eye::rtmp_stopRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace roller_eye

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::roller_eye::rtmp_stopRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roller_eye::rtmp_stopRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roller_eye::rtmp_stopRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roller_eye::rtmp_stopRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roller_eye::rtmp_stopRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roller_eye::rtmp_stopRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roller_eye::rtmp_stopRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7407dfac20b4d5473ccb56992a34f770";
  }

  static const char* value(const ::roller_eye::rtmp_stopRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7407dfac20b4d547ULL;
  static const uint64_t static_value2 = 0x3ccb56992a34f770ULL;
};

template<class ContainerAllocator>
struct DataType< ::roller_eye::rtmp_stopRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roller_eye/rtmp_stopRequest";
  }

  static const char* value(const ::roller_eye::rtmp_stopRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roller_eye::rtmp_stopRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string app\n"
"string name\n"
;
  }

  static const char* value(const ::roller_eye::rtmp_stopRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roller_eye::rtmp_stopRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.app);
      stream.next(m.name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct rtmp_stopRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roller_eye::rtmp_stopRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roller_eye::rtmp_stopRequest_<ContainerAllocator>& v)
  {
    s << indent << "app: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.app);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROLLER_EYE_MESSAGE_RTMP_STOPREQUEST_H
