// Generated by gencpp from file roller_eye/rtmp_stopResponse.msg
// DO NOT EDIT!


#ifndef ROLLER_EYE_MESSAGE_RTMP_STOPRESPONSE_H
#define ROLLER_EYE_MESSAGE_RTMP_STOPRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roller_eye
{
template <class ContainerAllocator>
struct rtmp_stopResponse_
{
  typedef rtmp_stopResponse_<ContainerAllocator> Type;

  rtmp_stopResponse_()
    : result(0)  {
    }
  rtmp_stopResponse_(const ContainerAllocator& _alloc)
    : result(0)  {
  (void)_alloc;
    }



   typedef int8_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::roller_eye::rtmp_stopResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roller_eye::rtmp_stopResponse_<ContainerAllocator> const> ConstPtr;

}; // struct rtmp_stopResponse_

typedef ::roller_eye::rtmp_stopResponse_<std::allocator<void> > rtmp_stopResponse;

typedef boost::shared_ptr< ::roller_eye::rtmp_stopResponse > rtmp_stopResponsePtr;
typedef boost::shared_ptr< ::roller_eye::rtmp_stopResponse const> rtmp_stopResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roller_eye::rtmp_stopResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roller_eye::rtmp_stopResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::roller_eye::rtmp_stopResponse_<ContainerAllocator1> & lhs, const ::roller_eye::rtmp_stopResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::roller_eye::rtmp_stopResponse_<ContainerAllocator1> & lhs, const ::roller_eye::rtmp_stopResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace roller_eye

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::roller_eye::rtmp_stopResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roller_eye::rtmp_stopResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roller_eye::rtmp_stopResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roller_eye::rtmp_stopResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roller_eye::rtmp_stopResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roller_eye::rtmp_stopResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roller_eye::rtmp_stopResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4414c67819626a1b8e0f043a9a0d6c9a";
  }

  static const char* value(const ::roller_eye::rtmp_stopResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4414c67819626a1bULL;
  static const uint64_t static_value2 = 0x8e0f043a9a0d6c9aULL;
};

template<class ContainerAllocator>
struct DataType< ::roller_eye::rtmp_stopResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roller_eye/rtmp_stopResponse";
  }

  static const char* value(const ::roller_eye::rtmp_stopResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roller_eye::rtmp_stopResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 result\n"
;
  }

  static const char* value(const ::roller_eye::rtmp_stopResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roller_eye::rtmp_stopResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct rtmp_stopResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roller_eye::rtmp_stopResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roller_eye::rtmp_stopResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<int8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROLLER_EYE_MESSAGE_RTMP_STOPRESPONSE_H
