// Generated by gencpp from file roller_eye/wifi_switch_ssid_keyRequest.msg
// DO NOT EDIT!


#ifndef ROLLER_EYE_MESSAGE_WIFI_SWITCH_SSID_KEYREQUEST_H
#define ROLLER_EYE_MESSAGE_WIFI_SWITCH_SSID_KEYREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roller_eye
{
template <class ContainerAllocator>
struct wifi_switch_ssid_keyRequest_
{
  typedef wifi_switch_ssid_keyRequest_<ContainerAllocator> Type;

  wifi_switch_ssid_keyRequest_()
    : mode(0)
    , ssid()
    , key()  {
    }
  wifi_switch_ssid_keyRequest_(const ContainerAllocator& _alloc)
    : mode(0)
    , ssid(_alloc)
    , key(_alloc)  {
  (void)_alloc;
    }



   typedef int8_t _mode_type;
  _mode_type mode;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _ssid_type;
  _ssid_type ssid;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _key_type;
  _key_type key;





  typedef boost::shared_ptr< ::roller_eye::wifi_switch_ssid_keyRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roller_eye::wifi_switch_ssid_keyRequest_<ContainerAllocator> const> ConstPtr;

}; // struct wifi_switch_ssid_keyRequest_

typedef ::roller_eye::wifi_switch_ssid_keyRequest_<std::allocator<void> > wifi_switch_ssid_keyRequest;

typedef boost::shared_ptr< ::roller_eye::wifi_switch_ssid_keyRequest > wifi_switch_ssid_keyRequestPtr;
typedef boost::shared_ptr< ::roller_eye::wifi_switch_ssid_keyRequest const> wifi_switch_ssid_keyRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roller_eye::wifi_switch_ssid_keyRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roller_eye::wifi_switch_ssid_keyRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::roller_eye::wifi_switch_ssid_keyRequest_<ContainerAllocator1> & lhs, const ::roller_eye::wifi_switch_ssid_keyRequest_<ContainerAllocator2> & rhs)
{
  return lhs.mode == rhs.mode &&
    lhs.ssid == rhs.ssid &&
    lhs.key == rhs.key;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::roller_eye::wifi_switch_ssid_keyRequest_<ContainerAllocator1> & lhs, const ::roller_eye::wifi_switch_ssid_keyRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace roller_eye

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::roller_eye::wifi_switch_ssid_keyRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roller_eye::wifi_switch_ssid_keyRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roller_eye::wifi_switch_ssid_keyRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roller_eye::wifi_switch_ssid_keyRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roller_eye::wifi_switch_ssid_keyRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roller_eye::wifi_switch_ssid_keyRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roller_eye::wifi_switch_ssid_keyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9f7a3d5203e4d0a2f29c292b00558c1a";
  }

  static const char* value(const ::roller_eye::wifi_switch_ssid_keyRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9f7a3d5203e4d0a2ULL;
  static const uint64_t static_value2 = 0xf29c292b00558c1aULL;
};

template<class ContainerAllocator>
struct DataType< ::roller_eye::wifi_switch_ssid_keyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roller_eye/wifi_switch_ssid_keyRequest";
  }

  static const char* value(const ::roller_eye::wifi_switch_ssid_keyRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roller_eye::wifi_switch_ssid_keyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 mode\n"
"string ssid\n"
"string key\n"
;
  }

  static const char* value(const ::roller_eye::wifi_switch_ssid_keyRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roller_eye::wifi_switch_ssid_keyRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
      stream.next(m.ssid);
      stream.next(m.key);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct wifi_switch_ssid_keyRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roller_eye::wifi_switch_ssid_keyRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roller_eye::wifi_switch_ssid_keyRequest_<ContainerAllocator>& v)
  {
    s << indent << "mode: ";
    Printer<int8_t>::stream(s, indent + "  ", v.mode);
    s << indent << "ssid: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.ssid);
    s << indent << "key: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.key);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROLLER_EYE_MESSAGE_WIFI_SWITCH_SSID_KEYREQUEST_H
