// Generated by gencpp from file roller_eye/wifi_config_info.msg
// DO NOT EDIT!


#ifndef ROLLER_EYE_MESSAGE_WIFI_CONFIG_INFO_H
#define ROLLER_EYE_MESSAGE_WIFI_CONFIG_INFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roller_eye
{
template <class ContainerAllocator>
struct wifi_config_info_
{
  typedef wifi_config_info_<ContainerAllocator> Type;

  wifi_config_info_()
    : cmd(0)
    , ssid()  {
    }
  wifi_config_info_(const ContainerAllocator& _alloc)
    : cmd(0)
    , ssid(_alloc)  {
  (void)_alloc;
    }



   typedef int8_t _cmd_type;
  _cmd_type cmd;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _ssid_type;
  _ssid_type ssid;





  typedef boost::shared_ptr< ::roller_eye::wifi_config_info_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roller_eye::wifi_config_info_<ContainerAllocator> const> ConstPtr;

}; // struct wifi_config_info_

typedef ::roller_eye::wifi_config_info_<std::allocator<void> > wifi_config_info;

typedef boost::shared_ptr< ::roller_eye::wifi_config_info > wifi_config_infoPtr;
typedef boost::shared_ptr< ::roller_eye::wifi_config_info const> wifi_config_infoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roller_eye::wifi_config_info_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roller_eye::wifi_config_info_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::roller_eye::wifi_config_info_<ContainerAllocator1> & lhs, const ::roller_eye::wifi_config_info_<ContainerAllocator2> & rhs)
{
  return lhs.cmd == rhs.cmd &&
    lhs.ssid == rhs.ssid;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::roller_eye::wifi_config_info_<ContainerAllocator1> & lhs, const ::roller_eye::wifi_config_info_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace roller_eye

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::roller_eye::wifi_config_info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roller_eye::wifi_config_info_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roller_eye::wifi_config_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roller_eye::wifi_config_info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roller_eye::wifi_config_info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roller_eye::wifi_config_info_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roller_eye::wifi_config_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "771488fba0e3eb08451a186125ca6c2a";
  }

  static const char* value(const ::roller_eye::wifi_config_info_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x771488fba0e3eb08ULL;
  static const uint64_t static_value2 = 0x451a186125ca6c2aULL;
};

template<class ContainerAllocator>
struct DataType< ::roller_eye::wifi_config_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roller_eye/wifi_config_info";
  }

  static const char* value(const ::roller_eye::wifi_config_info_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roller_eye::wifi_config_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#cmd: 0-start, 1- config success, 2-config failure\n"
"int8    cmd\n"
"string ssid\n"
;
  }

  static const char* value(const ::roller_eye::wifi_config_info_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roller_eye::wifi_config_info_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cmd);
      stream.next(m.ssid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct wifi_config_info_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roller_eye::wifi_config_info_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roller_eye::wifi_config_info_<ContainerAllocator>& v)
  {
    s << indent << "cmd: ";
    Printer<int8_t>::stream(s, indent + "  ", v.cmd);
    s << indent << "ssid: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.ssid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROLLER_EYE_MESSAGE_WIFI_CONFIG_INFO_H
