(cl:in-package roller_eye-msg)
(cl:export '(ID-VAL
          ID
          NAME-VAL
          NAME
          TYPE-VAL
          TYPE
          REPEATETYPE-VAL
          REPEATETYPE
          REPEATEDAYS-VAL
          REPEATEDAYS
          TIMEYEAR-VAL
          TIMEYEAR
          TIMEMONTH-VAL
          TIMEMONTH
          TIMEDAY-VAL
          TIMEDAY
          TIMEHOUR-VAL
          TIMEHOUR
          TIMEMINUTE-VAL
          TIMEMINUTE
          TIMESECOND-VAL
          TIMESECOND
          EXPIRE-VAL
          EXPIRE
          PARAM-VAL
          PARAM
          NOTICE-VAL
          NOTICE
          ACTIVE-VAL
          ACTIVE
))