; Auto-generated. Do not edit!


(cl:in-package roller_eye-msg)


;//! \htmlinclude status.msg.html

(cl:defclass <status> (roslisp-msg-protocol:ros-message)
  ((status
    :reader status
    :initarg :status
    :type (cl:vector cl:integer)
   :initform (cl:make-array 0 :element-type 'cl:integer :initial-element 0)))
)

(cl:defclass status (<status>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <status>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'status)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name roller_eye-msg:<status> is deprecated: use roller_eye-msg:status instead.")))

(cl:ensure-generic-function 'status-val :lambda-list '(m))
(cl:defmethod status-val ((m <status>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader roller_eye-msg:status-val is deprecated.  Use roller_eye-msg:status instead.")
  (status m))
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql '<status>)))
    "Constants for message type '<status>"
  '((:PROCESS_OK . 0)
    (:PROCESS_ERROR . -1)
    (:OBJ_DETECT_CHARGE . 1)
    (:RECORD_START . 1)
    (:RECORD_STOP . 2)
    (:RECORD_ERROR . 3)
    (:P2P_AV_PLAYING . 1)
    (:P2P_AV_STOP . 2)
    (:P2P_AV_ERROR . 3)
    (:WIFI_MODE_AP . 0)
    (:WIFI_MODE_STA . 1)
    (:WIFI_STATUS_DISCONNECT . 0)
    (:WIFI_STATUS_CONNECTED . 1)
    (:WIFI_STATUS_CONNECTING . 2)
    (:WIFI_STATUS_WRONG_KEY . 3)
    (:WIFI_STATUS_CONN_FAIL . 4)
    (:WIFI_STATUS_STOP . 5)
    (:BACK_UP_DETECT . 1)
    (:BACK_UP_ALIGN . 2)
    (:BACK_UP_BACK . 3)
    (:BACK_UP_SUCCESS . 4)
    (:BACK_UP_FAIL . 5)
    (:BACK_UP_INACTIVE . 6)
    (:BACK_UP_CANCEL . 7)
    (:BACK_UP_REDETECT . 8)
    (:BATTERY_CHARGING . 0)
    (:BATTERY_UNCHARGE . 1)
    (:BATTERY_FULL . 2)
    (:BATTERY_UNKOWN . 3))
)
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql 'status)))
    "Constants for message type 'status"
  '((:PROCESS_OK . 0)
    (:PROCESS_ERROR . -1)
    (:OBJ_DETECT_CHARGE . 1)
    (:RECORD_START . 1)
    (:RECORD_STOP . 2)
    (:RECORD_ERROR . 3)
    (:P2P_AV_PLAYING . 1)
    (:P2P_AV_STOP . 2)
    (:P2P_AV_ERROR . 3)
    (:WIFI_MODE_AP . 0)
    (:WIFI_MODE_STA . 1)
    (:WIFI_STATUS_DISCONNECT . 0)
    (:WIFI_STATUS_CONNECTED . 1)
    (:WIFI_STATUS_CONNECTING . 2)
    (:WIFI_STATUS_WRONG_KEY . 3)
    (:WIFI_STATUS_CONN_FAIL . 4)
    (:WIFI_STATUS_STOP . 5)
    (:BACK_UP_DETECT . 1)
    (:BACK_UP_ALIGN . 2)
    (:BACK_UP_BACK . 3)
    (:BACK_UP_SUCCESS . 4)
    (:BACK_UP_FAIL . 5)
    (:BACK_UP_INACTIVE . 6)
    (:BACK_UP_CANCEL . 7)
    (:BACK_UP_REDETECT . 8)
    (:BATTERY_CHARGING . 0)
    (:BATTERY_UNCHARGE . 1)
    (:BATTERY_FULL . 2)
    (:BATTERY_UNKOWN . 3))
)
(cl:defmethod roslisp-msg-protocol:serialize ((msg <status>) ostream)
  "Serializes a message object of type '<status>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'status))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let* ((signed ele) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    ))
   (cl:slot-value msg 'status))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <status>) istream)
  "Deserializes a message object of type '<status>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'status) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'status)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296)))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<status>)))
  "Returns string type for a message object of type '<status>"
  "roller_eye/status")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'status)))
  "Returns string type for a message object of type 'status"
  "roller_eye/status")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<status>)))
  "Returns md5sum for a message object of type '<status>"
  "6919a5b3f28e39f677c7c81d4e5a2ef4")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'status)))
  "Returns md5sum for a message object of type 'status"
  "6919a5b3f28e39f677c7c81d4e5a2ef4")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<status>)))
  "Returns full string definition for message of type '<status>"
  (cl:format cl:nil "#error and ok~%int8 PROCESS_OK=0~%int8 PROCESS_ERROR=-1~%~%~%#const for object detecting~%int8 OBJ_DETECT_CHARGE=1~%~%~%#const for recording~%int8 RECORD_START=1~%int8 RECORD_STOP=2~%int8 RECORD_ERROR=3~%~%~%~%#const for p2p av module~%int8 P2P_AV_PLAYING=1~%int8 P2P_AV_STOP=2~%int8 P2P_AV_ERROR=3~%~%#const define for wifi~%int8 WIFI_MODE_AP=0~%int8 WIFI_MODE_STA=1~%~%int8 WIFI_STATUS_DISCONNECT=0~%int8 WIFI_STATUS_CONNECTED=1~%int8 WIFI_STATUS_CONNECTING=2~%int8 WIFI_STATUS_WRONG_KEY=3~%int8 WIFI_STATUS_CONN_FAIL=4~%int8 WIFI_STATUS_STOP=5~%~%int8 BACK_UP_DETECT=1~%int8 BACK_UP_ALIGN=2~%int8 BACK_UP_BACK=3~%int8 BACK_UP_SUCCESS=4~%int8 BACK_UP_FAIL=5~%int8 BACK_UP_INACTIVE=6~%int8 BACK_UP_CANCEL=7~%int8 BACK_UP_REDETECT=8~%~%int8 BATTERY_CHARGING=0~%int8 BATTERY_UNCHARGE=1~%int8 BATTERY_FULL=2~%int8 BATTERY_UNKOWN=3~%~%#msg define~%int32[]  status~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'status)))
  "Returns full string definition for message of type 'status"
  (cl:format cl:nil "#error and ok~%int8 PROCESS_OK=0~%int8 PROCESS_ERROR=-1~%~%~%#const for object detecting~%int8 OBJ_DETECT_CHARGE=1~%~%~%#const for recording~%int8 RECORD_START=1~%int8 RECORD_STOP=2~%int8 RECORD_ERROR=3~%~%~%~%#const for p2p av module~%int8 P2P_AV_PLAYING=1~%int8 P2P_AV_STOP=2~%int8 P2P_AV_ERROR=3~%~%#const define for wifi~%int8 WIFI_MODE_AP=0~%int8 WIFI_MODE_STA=1~%~%int8 WIFI_STATUS_DISCONNECT=0~%int8 WIFI_STATUS_CONNECTED=1~%int8 WIFI_STATUS_CONNECTING=2~%int8 WIFI_STATUS_WRONG_KEY=3~%int8 WIFI_STATUS_CONN_FAIL=4~%int8 WIFI_STATUS_STOP=5~%~%int8 BACK_UP_DETECT=1~%int8 BACK_UP_ALIGN=2~%int8 BACK_UP_BACK=3~%int8 BACK_UP_SUCCESS=4~%int8 BACK_UP_FAIL=5~%int8 BACK_UP_INACTIVE=6~%int8 BACK_UP_CANCEL=7~%int8 BACK_UP_REDETECT=8~%~%int8 BATTERY_CHARGING=0~%int8 BATTERY_UNCHARGE=1~%int8 BATTERY_FULL=2~%int8 BATTERY_UNKOWN=3~%~%#msg define~%int32[]  status~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <status>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'status) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <status>))
  "Converts a ROS message object to a list"
  (cl:list 'status
    (cl:cons ':status (status msg))
))
