// Generated by gencpp from file roller_eye/nav_cancel.msg
// DO NOT EDIT!


#ifndef ROLLER_EYE_MESSAGE_NAV_CANCEL_H
#define ROLLER_EYE_MESSAGE_NAV_CANCEL_H

#include <ros/service_traits.h>


#include <roller_eye/nav_cancelRequest.h>
#include <roller_eye/nav_cancelResponse.h>


namespace roller_eye
{

struct nav_cancel
{

typedef nav_cancelRequest Request;
typedef nav_cancelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct nav_cancel
} // namespace roller_eye


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::roller_eye::nav_cancel > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::roller_eye::nav_cancel&) { return value(); }
};

template<>
struct DataType< ::roller_eye::nav_cancel > {
  static const char* value()
  {
    return "roller_eye/nav_cancel";
  }

  static const char* value(const ::roller_eye::nav_cancel&) { return value(); }
};


// service_traits::MD5Sum< ::roller_eye::nav_cancelRequest> should match
// service_traits::MD5Sum< ::roller_eye::nav_cancel >
template<>
struct MD5Sum< ::roller_eye::nav_cancelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::roller_eye::nav_cancel >::value();
  }
  static const char* value(const ::roller_eye::nav_cancelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::roller_eye::nav_cancelRequest> should match
// service_traits::DataType< ::roller_eye::nav_cancel >
template<>
struct DataType< ::roller_eye::nav_cancelRequest>
{
  static const char* value()
  {
    return DataType< ::roller_eye::nav_cancel >::value();
  }
  static const char* value(const ::roller_eye::nav_cancelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::roller_eye::nav_cancelResponse> should match
// service_traits::MD5Sum< ::roller_eye::nav_cancel >
template<>
struct MD5Sum< ::roller_eye::nav_cancelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::roller_eye::nav_cancel >::value();
  }
  static const char* value(const ::roller_eye::nav_cancelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::roller_eye::nav_cancelResponse> should match
// service_traits::DataType< ::roller_eye::nav_cancel >
template<>
struct DataType< ::roller_eye::nav_cancelResponse>
{
  static const char* value()
  {
    return DataType< ::roller_eye::nav_cancel >::value();
  }
  static const char* value(const ::roller_eye::nav_cancelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROLLER_EYE_MESSAGE_NAV_CANCEL_H
