// Generated by gencpp from file roller_eye/nav_patrol_stop.msg
// DO NOT EDIT!


#ifndef ROLLER_EYE_MESSAGE_NAV_PATROL_STOP_H
#define ROLLER_EYE_MESSAGE_NAV_PATROL_STOP_H

#include <ros/service_traits.h>


#include <roller_eye/nav_patrol_stopRequest.h>
#include <roller_eye/nav_patrol_stopResponse.h>


namespace roller_eye
{

struct nav_patrol_stop
{

typedef nav_patrol_stopRequest Request;
typedef nav_patrol_stopResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct nav_patrol_stop
} // namespace roller_eye


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::roller_eye::nav_patrol_stop > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::roller_eye::nav_patrol_stop&) { return value(); }
};

template<>
struct DataType< ::roller_eye::nav_patrol_stop > {
  static const char* value()
  {
    return "roller_eye/nav_patrol_stop";
  }

  static const char* value(const ::roller_eye::nav_patrol_stop&) { return value(); }
};


// service_traits::MD5Sum< ::roller_eye::nav_patrol_stopRequest> should match
// service_traits::MD5Sum< ::roller_eye::nav_patrol_stop >
template<>
struct MD5Sum< ::roller_eye::nav_patrol_stopRequest>
{
  static const char* value()
  {
    return MD5Sum< ::roller_eye::nav_patrol_stop >::value();
  }
  static const char* value(const ::roller_eye::nav_patrol_stopRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::roller_eye::nav_patrol_stopRequest> should match
// service_traits::DataType< ::roller_eye::nav_patrol_stop >
template<>
struct DataType< ::roller_eye::nav_patrol_stopRequest>
{
  static const char* value()
  {
    return DataType< ::roller_eye::nav_patrol_stop >::value();
  }
  static const char* value(const ::roller_eye::nav_patrol_stopRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::roller_eye::nav_patrol_stopResponse> should match
// service_traits::MD5Sum< ::roller_eye::nav_patrol_stop >
template<>
struct MD5Sum< ::roller_eye::nav_patrol_stopResponse>
{
  static const char* value()
  {
    return MD5Sum< ::roller_eye::nav_patrol_stop >::value();
  }
  static const char* value(const ::roller_eye::nav_patrol_stopResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::roller_eye::nav_patrol_stopResponse> should match
// service_traits::DataType< ::roller_eye::nav_patrol_stop >
template<>
struct DataType< ::roller_eye::nav_patrol_stopResponse>
{
  static const char* value()
  {
    return DataType< ::roller_eye::nav_patrol_stop >::value();
  }
  static const char* value(const ::roller_eye::nav_patrol_stopResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROLLER_EYE_MESSAGE_NAV_PATROL_STOP_H
