// Generated by gencpp from file roller_eye/nav_delete_pathRequest.msg
// DO NOT EDIT!


#ifndef ROLLER_EYE_MESSAGE_NAV_DELETE_PATHREQUEST_H
#define ROLLER_EYE_MESSAGE_NAV_DELETE_PATHREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roller_eye
{
template <class ContainerAllocator>
struct nav_delete_pathRequest_
{
  typedef nav_delete_pathRequest_<ContainerAllocator> Type;

  nav_delete_pathRequest_()
    : names()  {
    }
  nav_delete_pathRequest_(const ContainerAllocator& _alloc)
    : names(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _names_type;
  _names_type names;





  typedef boost::shared_ptr< ::roller_eye::nav_delete_pathRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roller_eye::nav_delete_pathRequest_<ContainerAllocator> const> ConstPtr;

}; // struct nav_delete_pathRequest_

typedef ::roller_eye::nav_delete_pathRequest_<std::allocator<void> > nav_delete_pathRequest;

typedef boost::shared_ptr< ::roller_eye::nav_delete_pathRequest > nav_delete_pathRequestPtr;
typedef boost::shared_ptr< ::roller_eye::nav_delete_pathRequest const> nav_delete_pathRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roller_eye::nav_delete_pathRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roller_eye::nav_delete_pathRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::roller_eye::nav_delete_pathRequest_<ContainerAllocator1> & lhs, const ::roller_eye::nav_delete_pathRequest_<ContainerAllocator2> & rhs)
{
  return lhs.names == rhs.names;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::roller_eye::nav_delete_pathRequest_<ContainerAllocator1> & lhs, const ::roller_eye::nav_delete_pathRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace roller_eye

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::roller_eye::nav_delete_pathRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roller_eye::nav_delete_pathRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roller_eye::nav_delete_pathRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roller_eye::nav_delete_pathRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roller_eye::nav_delete_pathRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roller_eye::nav_delete_pathRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roller_eye::nav_delete_pathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dc7ae3609524b18034e49294a4ce670e";
  }

  static const char* value(const ::roller_eye::nav_delete_pathRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdc7ae3609524b180ULL;
  static const uint64_t static_value2 = 0x34e49294a4ce670eULL;
};

template<class ContainerAllocator>
struct DataType< ::roller_eye::nav_delete_pathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roller_eye/nav_delete_pathRequest";
  }

  static const char* value(const ::roller_eye::nav_delete_pathRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roller_eye::nav_delete_pathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] names\n"
;
  }

  static const char* value(const ::roller_eye::nav_delete_pathRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roller_eye::nav_delete_pathRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.names);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct nav_delete_pathRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roller_eye::nav_delete_pathRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roller_eye::nav_delete_pathRequest_<ContainerAllocator>& v)
  {
    s << indent << "names[]" << std::endl;
    for (size_t i = 0; i < v.names.size(); ++i)
    {
      s << indent << "  names[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.names[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROLLER_EYE_MESSAGE_NAV_DELETE_PATHREQUEST_H
