// Generated by gencpp from file roller_eye/nav_path_saveRequest.msg
// DO NOT EDIT!


#ifndef ROLLER_EYE_MESSAGE_NAV_PATH_SAVEREQUEST_H
#define ROLLER_EYE_MESSAGE_NAV_PATH_SAVEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roller_eye
{
template <class ContainerAllocator>
struct nav_path_saveRequest_
{
  typedef nav_path_saveRequest_<ContainerAllocator> Type;

  nav_path_saveRequest_()
    : name()  {
    }
  nav_path_saveRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;





  typedef boost::shared_ptr< ::roller_eye::nav_path_saveRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roller_eye::nav_path_saveRequest_<ContainerAllocator> const> ConstPtr;

}; // struct nav_path_saveRequest_

typedef ::roller_eye::nav_path_saveRequest_<std::allocator<void> > nav_path_saveRequest;

typedef boost::shared_ptr< ::roller_eye::nav_path_saveRequest > nav_path_saveRequestPtr;
typedef boost::shared_ptr< ::roller_eye::nav_path_saveRequest const> nav_path_saveRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roller_eye::nav_path_saveRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roller_eye::nav_path_saveRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::roller_eye::nav_path_saveRequest_<ContainerAllocator1> & lhs, const ::roller_eye::nav_path_saveRequest_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::roller_eye::nav_path_saveRequest_<ContainerAllocator1> & lhs, const ::roller_eye::nav_path_saveRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace roller_eye

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::roller_eye::nav_path_saveRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roller_eye::nav_path_saveRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roller_eye::nav_path_saveRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roller_eye::nav_path_saveRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roller_eye::nav_path_saveRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roller_eye::nav_path_saveRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roller_eye::nav_path_saveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c1f3d28f1b044c871e6eff2e9fc3c667";
  }

  static const char* value(const ::roller_eye::nav_path_saveRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc1f3d28f1b044c87ULL;
  static const uint64_t static_value2 = 0x1e6eff2e9fc3c667ULL;
};

template<class ContainerAllocator>
struct DataType< ::roller_eye::nav_path_saveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roller_eye/nav_path_saveRequest";
  }

  static const char* value(const ::roller_eye::nav_path_saveRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roller_eye::nav_path_saveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
;
  }

  static const char* value(const ::roller_eye::nav_path_saveRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roller_eye::nav_path_saveRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct nav_path_saveRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roller_eye::nav_path_saveRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roller_eye::nav_path_saveRequest_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROLLER_EYE_MESSAGE_NAV_PATH_SAVEREQUEST_H
