// Generated by gencpp from file roller_eye/nav_get_patrol_name.msg
// DO NOT EDIT!


#ifndef ROLLER_EYE_MESSAGE_NAV_GET_PATROL_NAME_H
#define ROLLER_EYE_MESSAGE_NAV_GET_PATROL_NAME_H

#include <ros/service_traits.h>


#include <roller_eye/nav_get_patrol_nameRequest.h>
#include <roller_eye/nav_get_patrol_nameResponse.h>


namespace roller_eye
{

struct nav_get_patrol_name
{

typedef nav_get_patrol_nameRequest Request;
typedef nav_get_patrol_nameResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct nav_get_patrol_name
} // namespace roller_eye


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::roller_eye::nav_get_patrol_name > {
  static const char* value()
  {
    return "c1f3d28f1b044c871e6eff2e9fc3c667";
  }

  static const char* value(const ::roller_eye::nav_get_patrol_name&) { return value(); }
};

template<>
struct DataType< ::roller_eye::nav_get_patrol_name > {
  static const char* value()
  {
    return "roller_eye/nav_get_patrol_name";
  }

  static const char* value(const ::roller_eye::nav_get_patrol_name&) { return value(); }
};


// service_traits::MD5Sum< ::roller_eye::nav_get_patrol_nameRequest> should match
// service_traits::MD5Sum< ::roller_eye::nav_get_patrol_name >
template<>
struct MD5Sum< ::roller_eye::nav_get_patrol_nameRequest>
{
  static const char* value()
  {
    return MD5Sum< ::roller_eye::nav_get_patrol_name >::value();
  }
  static const char* value(const ::roller_eye::nav_get_patrol_nameRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::roller_eye::nav_get_patrol_nameRequest> should match
// service_traits::DataType< ::roller_eye::nav_get_patrol_name >
template<>
struct DataType< ::roller_eye::nav_get_patrol_nameRequest>
{
  static const char* value()
  {
    return DataType< ::roller_eye::nav_get_patrol_name >::value();
  }
  static const char* value(const ::roller_eye::nav_get_patrol_nameRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::roller_eye::nav_get_patrol_nameResponse> should match
// service_traits::MD5Sum< ::roller_eye::nav_get_patrol_name >
template<>
struct MD5Sum< ::roller_eye::nav_get_patrol_nameResponse>
{
  static const char* value()
  {
    return MD5Sum< ::roller_eye::nav_get_patrol_name >::value();
  }
  static const char* value(const ::roller_eye::nav_get_patrol_nameResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::roller_eye::nav_get_patrol_nameResponse> should match
// service_traits::DataType< ::roller_eye::nav_get_patrol_name >
template<>
struct DataType< ::roller_eye::nav_get_patrol_nameResponse>
{
  static const char* value()
  {
    return DataType< ::roller_eye::nav_get_patrol_name >::value();
  }
  static const char* value(const ::roller_eye::nav_get_patrol_nameResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROLLER_EYE_MESSAGE_NAV_GET_PATROL_NAME_H
