// Generated by gencpp from file roller_eye/nav_delete_path.msg
// DO NOT EDIT!


#ifndef ROLLER_EYE_MESSAGE_NAV_DELETE_PATH_H
#define ROLLER_EYE_MESSAGE_NAV_DELETE_PATH_H

#include <ros/service_traits.h>


#include <roller_eye/nav_delete_pathRequest.h>
#include <roller_eye/nav_delete_pathResponse.h>


namespace roller_eye
{

struct nav_delete_path
{

typedef nav_delete_pathRequest Request;
typedef nav_delete_pathResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct nav_delete_path
} // namespace roller_eye


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::roller_eye::nav_delete_path > {
  static const char* value()
  {
    return "dc7ae3609524b18034e49294a4ce670e";
  }

  static const char* value(const ::roller_eye::nav_delete_path&) { return value(); }
};

template<>
struct DataType< ::roller_eye::nav_delete_path > {
  static const char* value()
  {
    return "roller_eye/nav_delete_path";
  }

  static const char* value(const ::roller_eye::nav_delete_path&) { return value(); }
};


// service_traits::MD5Sum< ::roller_eye::nav_delete_pathRequest> should match
// service_traits::MD5Sum< ::roller_eye::nav_delete_path >
template<>
struct MD5Sum< ::roller_eye::nav_delete_pathRequest>
{
  static const char* value()
  {
    return MD5Sum< ::roller_eye::nav_delete_path >::value();
  }
  static const char* value(const ::roller_eye::nav_delete_pathRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::roller_eye::nav_delete_pathRequest> should match
// service_traits::DataType< ::roller_eye::nav_delete_path >
template<>
struct DataType< ::roller_eye::nav_delete_pathRequest>
{
  static const char* value()
  {
    return DataType< ::roller_eye::nav_delete_path >::value();
  }
  static const char* value(const ::roller_eye::nav_delete_pathRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::roller_eye::nav_delete_pathResponse> should match
// service_traits::MD5Sum< ::roller_eye::nav_delete_path >
template<>
struct MD5Sum< ::roller_eye::nav_delete_pathResponse>
{
  static const char* value()
  {
    return MD5Sum< ::roller_eye::nav_delete_path >::value();
  }
  static const char* value(const ::roller_eye::nav_delete_pathResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::roller_eye::nav_delete_pathResponse> should match
// service_traits::DataType< ::roller_eye::nav_delete_path >
template<>
struct DataType< ::roller_eye::nav_delete_pathResponse>
{
  static const char* value()
  {
    return DataType< ::roller_eye::nav_delete_path >::value();
  }
  static const char* value(const ::roller_eye::nav_delete_pathResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROLLER_EYE_MESSAGE_NAV_DELETE_PATH_H
