// Generated by gencpp from file roller_eye/record_delete_fileRequest.msg
// DO NOT EDIT!


#ifndef ROLLER_EYE_MESSAGE_RECORD_DELETE_FILEREQUEST_H
#define ROLLER_EYE_MESSAGE_RECORD_DELETE_FILEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roller_eye
{
template <class ContainerAllocator>
struct record_delete_fileRequest_
{
  typedef record_delete_fileRequest_<ContainerAllocator> Type;

  record_delete_fileRequest_()
    : id()  {
    }
  record_delete_fileRequest_(const ContainerAllocator& _alloc)
    : id(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _id_type;
  _id_type id;





  typedef boost::shared_ptr< ::roller_eye::record_delete_fileRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roller_eye::record_delete_fileRequest_<ContainerAllocator> const> ConstPtr;

}; // struct record_delete_fileRequest_

typedef ::roller_eye::record_delete_fileRequest_<std::allocator<void> > record_delete_fileRequest;

typedef boost::shared_ptr< ::roller_eye::record_delete_fileRequest > record_delete_fileRequestPtr;
typedef boost::shared_ptr< ::roller_eye::record_delete_fileRequest const> record_delete_fileRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roller_eye::record_delete_fileRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roller_eye::record_delete_fileRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::roller_eye::record_delete_fileRequest_<ContainerAllocator1> & lhs, const ::roller_eye::record_delete_fileRequest_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::roller_eye::record_delete_fileRequest_<ContainerAllocator1> & lhs, const ::roller_eye::record_delete_fileRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace roller_eye

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::roller_eye::record_delete_fileRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roller_eye::record_delete_fileRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roller_eye::record_delete_fileRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roller_eye::record_delete_fileRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roller_eye::record_delete_fileRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roller_eye::record_delete_fileRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roller_eye::record_delete_fileRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bbfcda76036ebbe3d36caf7af80b260c";
  }

  static const char* value(const ::roller_eye::record_delete_fileRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbbfcda76036ebbe3ULL;
  static const uint64_t static_value2 = 0xd36caf7af80b260cULL;
};

template<class ContainerAllocator>
struct DataType< ::roller_eye::record_delete_fileRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roller_eye/record_delete_fileRequest";
  }

  static const char* value(const ::roller_eye::record_delete_fileRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roller_eye::record_delete_fileRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#the id is used to indicate the record file\n"
"string id\n"
;
  }

  static const char* value(const ::roller_eye::record_delete_fileRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roller_eye::record_delete_fileRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct record_delete_fileRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roller_eye::record_delete_fileRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roller_eye::record_delete_fileRequest_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROLLER_EYE_MESSAGE_RECORD_DELETE_FILEREQUEST_H
