// Generated by gencpp from file roller_eye/record_startRequest.msg
// DO NOT EDIT!


#ifndef ROLLER_EYE_MESSAGE_RECORD_STARTREQUEST_H
#define ROLLER_EYE_MESSAGE_RECORD_STARTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roller_eye
{
template <class ContainerAllocator>
struct record_startRequest_
{
  typedef record_startRequest_<ContainerAllocator> Type;

  record_startRequest_()
    : type(0)
    , mode(0)
    , duration(0)
    , count(0)  {
    }
  record_startRequest_(const ContainerAllocator& _alloc)
    : type(0)
    , mode(0)
    , duration(0)
    , count(0)  {
  (void)_alloc;
    }



   typedef int8_t _type_type;
  _type_type type;

   typedef int8_t _mode_type;
  _mode_type mode;

   typedef uint32_t _duration_type;
  _duration_type duration;

   typedef int32_t _count_type;
  _count_type count;





  typedef boost::shared_ptr< ::roller_eye::record_startRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roller_eye::record_startRequest_<ContainerAllocator> const> ConstPtr;

}; // struct record_startRequest_

typedef ::roller_eye::record_startRequest_<std::allocator<void> > record_startRequest;

typedef boost::shared_ptr< ::roller_eye::record_startRequest > record_startRequestPtr;
typedef boost::shared_ptr< ::roller_eye::record_startRequest const> record_startRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roller_eye::record_startRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roller_eye::record_startRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::roller_eye::record_startRequest_<ContainerAllocator1> & lhs, const ::roller_eye::record_startRequest_<ContainerAllocator2> & rhs)
{
  return lhs.type == rhs.type &&
    lhs.mode == rhs.mode &&
    lhs.duration == rhs.duration &&
    lhs.count == rhs.count;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::roller_eye::record_startRequest_<ContainerAllocator1> & lhs, const ::roller_eye::record_startRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace roller_eye

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::roller_eye::record_startRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roller_eye::record_startRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roller_eye::record_startRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roller_eye::record_startRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roller_eye::record_startRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roller_eye::record_startRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roller_eye::record_startRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9606da2bae2c0f489c5ded4b8ee874c8";
  }

  static const char* value(const ::roller_eye::record_startRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9606da2bae2c0f48ULL;
  static const uint64_t static_value2 = 0x9c5ded4b8ee874c8ULL;
};

template<class ContainerAllocator>
struct DataType< ::roller_eye::record_startRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roller_eye/record_startRequest";
  }

  static const char* value(const ::roller_eye::record_startRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roller_eye::record_startRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# snapshot or record\n"
"int8 type\n"
"int8 mode\n"
"uint32 duration\n"
"int32 count\n"
;
  }

  static const char* value(const ::roller_eye::record_startRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roller_eye::record_startRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.type);
      stream.next(m.mode);
      stream.next(m.duration);
      stream.next(m.count);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct record_startRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roller_eye::record_startRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roller_eye::record_startRequest_<ContainerAllocator>& v)
  {
    s << indent << "type: ";
    Printer<int8_t>::stream(s, indent + "  ", v.type);
    s << indent << "mode: ";
    Printer<int8_t>::stream(s, indent + "  ", v.mode);
    s << indent << "duration: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.duration);
    s << indent << "count: ";
    Printer<int32_t>::stream(s, indent + "  ", v.count);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROLLER_EYE_MESSAGE_RECORD_STARTREQUEST_H
