// Generated by gencpp from file roller_eye/record_cleanResponse.msg
// DO NOT EDIT!


#ifndef ROLLER_EYE_MESSAGE_RECORD_CLEANRESPONSE_H
#define ROLLER_EYE_MESSAGE_RECORD_CLEANRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roller_eye
{
template <class ContainerAllocator>
struct record_cleanResponse_
{
  typedef record_cleanResponse_<ContainerAllocator> Type;

  record_cleanResponse_()
    {
    }
  record_cleanResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::roller_eye::record_cleanResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roller_eye::record_cleanResponse_<ContainerAllocator> const> ConstPtr;

}; // struct record_cleanResponse_

typedef ::roller_eye::record_cleanResponse_<std::allocator<void> > record_cleanResponse;

typedef boost::shared_ptr< ::roller_eye::record_cleanResponse > record_cleanResponsePtr;
typedef boost::shared_ptr< ::roller_eye::record_cleanResponse const> record_cleanResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roller_eye::record_cleanResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roller_eye::record_cleanResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace roller_eye

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::roller_eye::record_cleanResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roller_eye::record_cleanResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roller_eye::record_cleanResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roller_eye::record_cleanResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roller_eye::record_cleanResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roller_eye::record_cleanResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roller_eye::record_cleanResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::roller_eye::record_cleanResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::roller_eye::record_cleanResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roller_eye/record_cleanResponse";
  }

  static const char* value(const ::roller_eye::record_cleanResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roller_eye::record_cleanResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::roller_eye::record_cleanResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roller_eye::record_cleanResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct record_cleanResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roller_eye::record_cleanResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::roller_eye::record_cleanResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ROLLER_EYE_MESSAGE_RECORD_CLEANRESPONSE_H
