// Generated by gencpp from file roller_eye/record_get_file_numResponse.msg
// DO NOT EDIT!


#ifndef ROLLER_EYE_MESSAGE_RECORD_GET_FILE_NUMRESPONSE_H
#define ROLLER_EYE_MESSAGE_RECORD_GET_FILE_NUMRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roller_eye
{
template <class ContainerAllocator>
struct record_get_file_numResponse_
{
  typedef record_get_file_numResponse_<ContainerAllocator> Type;

  record_get_file_numResponse_()
    : count(0)  {
    }
  record_get_file_numResponse_(const ContainerAllocator& _alloc)
    : count(0)  {
  (void)_alloc;
    }



   typedef int32_t _count_type;
  _count_type count;





  typedef boost::shared_ptr< ::roller_eye::record_get_file_numResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roller_eye::record_get_file_numResponse_<ContainerAllocator> const> ConstPtr;

}; // struct record_get_file_numResponse_

typedef ::roller_eye::record_get_file_numResponse_<std::allocator<void> > record_get_file_numResponse;

typedef boost::shared_ptr< ::roller_eye::record_get_file_numResponse > record_get_file_numResponsePtr;
typedef boost::shared_ptr< ::roller_eye::record_get_file_numResponse const> record_get_file_numResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roller_eye::record_get_file_numResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roller_eye::record_get_file_numResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::roller_eye::record_get_file_numResponse_<ContainerAllocator1> & lhs, const ::roller_eye::record_get_file_numResponse_<ContainerAllocator2> & rhs)
{
  return lhs.count == rhs.count;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::roller_eye::record_get_file_numResponse_<ContainerAllocator1> & lhs, const ::roller_eye::record_get_file_numResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace roller_eye

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::roller_eye::record_get_file_numResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roller_eye::record_get_file_numResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roller_eye::record_get_file_numResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roller_eye::record_get_file_numResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roller_eye::record_get_file_numResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roller_eye::record_get_file_numResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roller_eye::record_get_file_numResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "602d642babe509c7c59f497c23e716a9";
  }

  static const char* value(const ::roller_eye::record_get_file_numResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x602d642babe509c7ULL;
  static const uint64_t static_value2 = 0xc59f497c23e716a9ULL;
};

template<class ContainerAllocator>
struct DataType< ::roller_eye::record_get_file_numResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roller_eye/record_get_file_numResponse";
  }

  static const char* value(const ::roller_eye::record_get_file_numResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roller_eye::record_get_file_numResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 count\n"
;
  }

  static const char* value(const ::roller_eye::record_get_file_numResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roller_eye::record_get_file_numResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.count);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct record_get_file_numResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roller_eye::record_get_file_numResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roller_eye::record_get_file_numResponse_<ContainerAllocator>& v)
  {
    s << indent << "count: ";
    Printer<int32_t>::stream(s, indent + "  ", v.count);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROLLER_EYE_MESSAGE_RECORD_GET_FILE_NUMRESPONSE_H
