// Generated by gencpp from file roller_eye/record_get_filesResponse.msg
// DO NOT EDIT!


#ifndef ROLLER_EYE_MESSAGE_RECORD_GET_FILESRESPONSE_H
#define ROLLER_EYE_MESSAGE_RECORD_GET_FILESRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <roller_eye/record.h>

namespace roller_eye
{
template <class ContainerAllocator>
struct record_get_filesResponse_
{
  typedef record_get_filesResponse_<ContainerAllocator> Type;

  record_get_filesResponse_()
    : files()  {
    }
  record_get_filesResponse_(const ContainerAllocator& _alloc)
    : files(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::roller_eye::record_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::roller_eye::record_<ContainerAllocator> >> _files_type;
  _files_type files;





  typedef boost::shared_ptr< ::roller_eye::record_get_filesResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roller_eye::record_get_filesResponse_<ContainerAllocator> const> ConstPtr;

}; // struct record_get_filesResponse_

typedef ::roller_eye::record_get_filesResponse_<std::allocator<void> > record_get_filesResponse;

typedef boost::shared_ptr< ::roller_eye::record_get_filesResponse > record_get_filesResponsePtr;
typedef boost::shared_ptr< ::roller_eye::record_get_filesResponse const> record_get_filesResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roller_eye::record_get_filesResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roller_eye::record_get_filesResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::roller_eye::record_get_filesResponse_<ContainerAllocator1> & lhs, const ::roller_eye::record_get_filesResponse_<ContainerAllocator2> & rhs)
{
  return lhs.files == rhs.files;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::roller_eye::record_get_filesResponse_<ContainerAllocator1> & lhs, const ::roller_eye::record_get_filesResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace roller_eye

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::roller_eye::record_get_filesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roller_eye::record_get_filesResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roller_eye::record_get_filesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roller_eye::record_get_filesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roller_eye::record_get_filesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roller_eye::record_get_filesResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roller_eye::record_get_filesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3eb0b1c52dafe591ce627d5472f2c69e";
  }

  static const char* value(const ::roller_eye::record_get_filesResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3eb0b1c52dafe591ULL;
  static const uint64_t static_value2 = 0xce627d5472f2c69eULL;
};

template<class ContainerAllocator>
struct DataType< ::roller_eye::record_get_filesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roller_eye/record_get_filesResponse";
  }

  static const char* value(const ::roller_eye::record_get_filesResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roller_eye::record_get_filesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "record[] files\n"
"\n"
"================================================================================\n"
"MSG: roller_eye/record\n"
"int8 RECORD_TYPE_ALL=0\n"
"int8 RECORD_TYPE_SNAPSHOT=1\n"
"int8 RECORD_TYPE_RECORD=2\n"
"int8 RECORD_TYPE_THUMB=3\n"
"int8 RECORD_TYPE_SCHED_RECORD=4\n"
"\n"
"#record file descriptor\n"
"string id\n"
"string name\n"
"uint32 dur\n"
"int8 type\n"
"time create\n"
"uint32 size\n"
;
  }

  static const char* value(const ::roller_eye::record_get_filesResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roller_eye::record_get_filesResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.files);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct record_get_filesResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roller_eye::record_get_filesResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roller_eye::record_get_filesResponse_<ContainerAllocator>& v)
  {
    s << indent << "files[]" << std::endl;
    for (size_t i = 0; i < v.files.size(); ++i)
    {
      s << indent << "  files[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::roller_eye::record_<ContainerAllocator> >::stream(s, indent + "    ", v.files[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROLLER_EYE_MESSAGE_RECORD_GET_FILESRESPONSE_H
