// Generated by gencpp from file roller_eye/rtmp_stop.msg
// DO NOT EDIT!


#ifndef ROLLER_EYE_MESSAGE_RTMP_STOP_H
#define ROLLER_EYE_MESSAGE_RTMP_STOP_H

#include <ros/service_traits.h>


#include <roller_eye/rtmp_stopRequest.h>
#include <roller_eye/rtmp_stopResponse.h>


namespace roller_eye
{

struct rtmp_stop
{

typedef rtmp_stopRequest Request;
typedef rtmp_stopResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct rtmp_stop
} // namespace roller_eye


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::roller_eye::rtmp_stop > {
  static const char* value()
  {
    return "f6dfd2cf4653c7fe4ab53921ea828817";
  }

  static const char* value(const ::roller_eye::rtmp_stop&) { return value(); }
};

template<>
struct DataType< ::roller_eye::rtmp_stop > {
  static const char* value()
  {
    return "roller_eye/rtmp_stop";
  }

  static const char* value(const ::roller_eye::rtmp_stop&) { return value(); }
};


// service_traits::MD5Sum< ::roller_eye::rtmp_stopRequest> should match
// service_traits::MD5Sum< ::roller_eye::rtmp_stop >
template<>
struct MD5Sum< ::roller_eye::rtmp_stopRequest>
{
  static const char* value()
  {
    return MD5Sum< ::roller_eye::rtmp_stop >::value();
  }
  static const char* value(const ::roller_eye::rtmp_stopRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::roller_eye::rtmp_stopRequest> should match
// service_traits::DataType< ::roller_eye::rtmp_stop >
template<>
struct DataType< ::roller_eye::rtmp_stopRequest>
{
  static const char* value()
  {
    return DataType< ::roller_eye::rtmp_stop >::value();
  }
  static const char* value(const ::roller_eye::rtmp_stopRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::roller_eye::rtmp_stopResponse> should match
// service_traits::MD5Sum< ::roller_eye::rtmp_stop >
template<>
struct MD5Sum< ::roller_eye::rtmp_stopResponse>
{
  static const char* value()
  {
    return MD5Sum< ::roller_eye::rtmp_stop >::value();
  }
  static const char* value(const ::roller_eye::rtmp_stopResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::roller_eye::rtmp_stopResponse> should match
// service_traits::DataType< ::roller_eye::rtmp_stop >
template<>
struct DataType< ::roller_eye::rtmp_stopResponse>
{
  static const char* value()
  {
    return DataType< ::roller_eye::rtmp_stop >::value();
  }
  static const char* value(const ::roller_eye::rtmp_stopResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROLLER_EYE_MESSAGE_RTMP_STOP_H
