// Generated by gencpp from file roller_eye/sched_add_mod.msg
// DO NOT EDIT!


#ifndef ROLLER_EYE_MESSAGE_SCHED_ADD_MOD_H
#define ROLLER_EYE_MESSAGE_SCHED_ADD_MOD_H

#include <ros/service_traits.h>


#include <roller_eye/sched_add_modRequest.h>
#include <roller_eye/sched_add_modResponse.h>


namespace roller_eye
{

struct sched_add_mod
{

typedef sched_add_modRequest Request;
typedef sched_add_modResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct sched_add_mod
} // namespace roller_eye


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::roller_eye::sched_add_mod > {
  static const char* value()
  {
    return "e0be7b42d9f9c638e488c09d9f0ede84";
  }

  static const char* value(const ::roller_eye::sched_add_mod&) { return value(); }
};

template<>
struct DataType< ::roller_eye::sched_add_mod > {
  static const char* value()
  {
    return "roller_eye/sched_add_mod";
  }

  static const char* value(const ::roller_eye::sched_add_mod&) { return value(); }
};


// service_traits::MD5Sum< ::roller_eye::sched_add_modRequest> should match
// service_traits::MD5Sum< ::roller_eye::sched_add_mod >
template<>
struct MD5Sum< ::roller_eye::sched_add_modRequest>
{
  static const char* value()
  {
    return MD5Sum< ::roller_eye::sched_add_mod >::value();
  }
  static const char* value(const ::roller_eye::sched_add_modRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::roller_eye::sched_add_modRequest> should match
// service_traits::DataType< ::roller_eye::sched_add_mod >
template<>
struct DataType< ::roller_eye::sched_add_modRequest>
{
  static const char* value()
  {
    return DataType< ::roller_eye::sched_add_mod >::value();
  }
  static const char* value(const ::roller_eye::sched_add_modRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::roller_eye::sched_add_modResponse> should match
// service_traits::MD5Sum< ::roller_eye::sched_add_mod >
template<>
struct MD5Sum< ::roller_eye::sched_add_modResponse>
{
  static const char* value()
  {
    return MD5Sum< ::roller_eye::sched_add_mod >::value();
  }
  static const char* value(const ::roller_eye::sched_add_modResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::roller_eye::sched_add_modResponse> should match
// service_traits::DataType< ::roller_eye::sched_add_mod >
template<>
struct DataType< ::roller_eye::sched_add_modResponse>
{
  static const char* value()
  {
    return DataType< ::roller_eye::sched_add_mod >::value();
  }
  static const char* value(const ::roller_eye::sched_add_modResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROLLER_EYE_MESSAGE_SCHED_ADD_MOD_H
