// Generated by gencpp from file roller_eye/sched_add_modResponse.msg
// DO NOT EDIT!


#ifndef ROLLER_EYE_MESSAGE_SCHED_ADD_MODRESPONSE_H
#define ROLLER_EYE_MESSAGE_SCHED_ADD_MODRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roller_eye
{
template <class ContainerAllocator>
struct sched_add_modResponse_
{
  typedef sched_add_modResponse_<ContainerAllocator> Type;

  sched_add_modResponse_()
    : id(0)  {
    }
  sched_add_modResponse_(const ContainerAllocator& _alloc)
    : id(0)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;





  typedef boost::shared_ptr< ::roller_eye::sched_add_modResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roller_eye::sched_add_modResponse_<ContainerAllocator> const> ConstPtr;

}; // struct sched_add_modResponse_

typedef ::roller_eye::sched_add_modResponse_<std::allocator<void> > sched_add_modResponse;

typedef boost::shared_ptr< ::roller_eye::sched_add_modResponse > sched_add_modResponsePtr;
typedef boost::shared_ptr< ::roller_eye::sched_add_modResponse const> sched_add_modResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roller_eye::sched_add_modResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roller_eye::sched_add_modResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::roller_eye::sched_add_modResponse_<ContainerAllocator1> & lhs, const ::roller_eye::sched_add_modResponse_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::roller_eye::sched_add_modResponse_<ContainerAllocator1> & lhs, const ::roller_eye::sched_add_modResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace roller_eye

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::roller_eye::sched_add_modResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roller_eye::sched_add_modResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roller_eye::sched_add_modResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roller_eye::sched_add_modResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roller_eye::sched_add_modResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roller_eye::sched_add_modResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roller_eye::sched_add_modResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c5e4a7d59c68f74eabcec876a00216aa";
  }

  static const char* value(const ::roller_eye::sched_add_modResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc5e4a7d59c68f74eULL;
  static const uint64_t static_value2 = 0xabcec876a00216aaULL;
};

template<class ContainerAllocator>
struct DataType< ::roller_eye::sched_add_modResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roller_eye/sched_add_modResponse";
  }

  static const char* value(const ::roller_eye::sched_add_modResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roller_eye::sched_add_modResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 id\n"
"\n"
"\n"
;
  }

  static const char* value(const ::roller_eye::sched_add_modResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roller_eye::sched_add_modResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct sched_add_modResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roller_eye::sched_add_modResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roller_eye::sched_add_modResponse_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROLLER_EYE_MESSAGE_SCHED_ADD_MODRESPONSE_H
