// Generated by gencpp from file roller_eye/wifi_scan_listResponse.msg
// DO NOT EDIT!


#ifndef ROLLER_EYE_MESSAGE_WIFI_SCAN_LISTRESPONSE_H
#define ROLLER_EYE_MESSAGE_WIFI_SCAN_LISTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <roller_eye/wifi_info.h>

namespace roller_eye
{
template <class ContainerAllocator>
struct wifi_scan_listResponse_
{
  typedef wifi_scan_listResponse_<ContainerAllocator> Type;

  wifi_scan_listResponse_()
    : result()  {
    }
  wifi_scan_listResponse_(const ContainerAllocator& _alloc)
    : result(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::roller_eye::wifi_info_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::roller_eye::wifi_info_<ContainerAllocator> >> _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::roller_eye::wifi_scan_listResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roller_eye::wifi_scan_listResponse_<ContainerAllocator> const> ConstPtr;

}; // struct wifi_scan_listResponse_

typedef ::roller_eye::wifi_scan_listResponse_<std::allocator<void> > wifi_scan_listResponse;

typedef boost::shared_ptr< ::roller_eye::wifi_scan_listResponse > wifi_scan_listResponsePtr;
typedef boost::shared_ptr< ::roller_eye::wifi_scan_listResponse const> wifi_scan_listResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roller_eye::wifi_scan_listResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roller_eye::wifi_scan_listResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::roller_eye::wifi_scan_listResponse_<ContainerAllocator1> & lhs, const ::roller_eye::wifi_scan_listResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::roller_eye::wifi_scan_listResponse_<ContainerAllocator1> & lhs, const ::roller_eye::wifi_scan_listResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace roller_eye

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::roller_eye::wifi_scan_listResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roller_eye::wifi_scan_listResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roller_eye::wifi_scan_listResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roller_eye::wifi_scan_listResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roller_eye::wifi_scan_listResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roller_eye::wifi_scan_listResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roller_eye::wifi_scan_listResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fd54a28d4e6325d269f60a72dc202a7b";
  }

  static const char* value(const ::roller_eye::wifi_scan_listResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfd54a28d4e6325d2ULL;
  static const uint64_t static_value2 = 0x69f60a72dc202a7bULL;
};

template<class ContainerAllocator>
struct DataType< ::roller_eye::wifi_scan_listResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roller_eye/wifi_scan_listResponse";
  }

  static const char* value(const ::roller_eye::wifi_scan_listResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roller_eye::wifi_scan_listResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wifi_info[] result\n"
"\n"
"================================================================================\n"
"MSG: roller_eye/wifi_info\n"
"string ssid\n"
"float32 quality\n"
"int32 signal\n"
"int32 noisy\n"
"float32 freq\n"
"int32 channel\n"
;
  }

  static const char* value(const ::roller_eye::wifi_scan_listResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roller_eye::wifi_scan_listResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct wifi_scan_listResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roller_eye::wifi_scan_listResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roller_eye::wifi_scan_listResponse_<ContainerAllocator>& v)
  {
    s << indent << "result[]" << std::endl;
    for (size_t i = 0; i < v.result.size(); ++i)
    {
      s << indent << "  result[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::roller_eye::wifi_info_<ContainerAllocator> >::stream(s, indent + "    ", v.result[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROLLER_EYE_MESSAGE_WIFI_SCAN_LISTRESPONSE_H
