// Generated by gencpp from file roller_eye/wifi_switch_modeResponse.msg
// DO NOT EDIT!


#ifndef ROLLER_EYE_MESSAGE_WIFI_SWITCH_MODERESPONSE_H
#define ROLLER_EYE_MESSAGE_WIFI_SWITCH_MODERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roller_eye
{
template <class ContainerAllocator>
struct wifi_switch_modeResponse_
{
  typedef wifi_switch_modeResponse_<ContainerAllocator> Type;

  wifi_switch_modeResponse_()
    : status(0)  {
    }
  wifi_switch_modeResponse_(const ContainerAllocator& _alloc)
    : status(0)  {
  (void)_alloc;
    }



   typedef int8_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::roller_eye::wifi_switch_modeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roller_eye::wifi_switch_modeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct wifi_switch_modeResponse_

typedef ::roller_eye::wifi_switch_modeResponse_<std::allocator<void> > wifi_switch_modeResponse;

typedef boost::shared_ptr< ::roller_eye::wifi_switch_modeResponse > wifi_switch_modeResponsePtr;
typedef boost::shared_ptr< ::roller_eye::wifi_switch_modeResponse const> wifi_switch_modeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roller_eye::wifi_switch_modeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roller_eye::wifi_switch_modeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::roller_eye::wifi_switch_modeResponse_<ContainerAllocator1> & lhs, const ::roller_eye::wifi_switch_modeResponse_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::roller_eye::wifi_switch_modeResponse_<ContainerAllocator1> & lhs, const ::roller_eye::wifi_switch_modeResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace roller_eye

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::roller_eye::wifi_switch_modeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roller_eye::wifi_switch_modeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roller_eye::wifi_switch_modeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roller_eye::wifi_switch_modeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roller_eye::wifi_switch_modeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roller_eye::wifi_switch_modeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roller_eye::wifi_switch_modeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "581cc55c12abfc219e446416014f6d0e";
  }

  static const char* value(const ::roller_eye::wifi_switch_modeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x581cc55c12abfc21ULL;
  static const uint64_t static_value2 = 0x9e446416014f6d0eULL;
};

template<class ContainerAllocator>
struct DataType< ::roller_eye::wifi_switch_modeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roller_eye/wifi_switch_modeResponse";
  }

  static const char* value(const ::roller_eye::wifi_switch_modeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roller_eye::wifi_switch_modeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 status\n"
;
  }

  static const char* value(const ::roller_eye::wifi_switch_modeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roller_eye::wifi_switch_modeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct wifi_switch_modeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roller_eye::wifi_switch_modeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roller_eye::wifi_switch_modeResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<int8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROLLER_EYE_MESSAGE_WIFI_SWITCH_MODERESPONSE_H
